/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audits */
        get: operations["list_audits_audits_get"];
        put?: never;
        /** Create Audit */
        post: operations["create_audit_audits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audits/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit */
        get: operations["get_audit_audits__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Engines */
        get: operations["list_engines_engines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Brand */
        post: operations["add_brand_projects__project_id__brands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_projects__project_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Prompt */
        post: operations["add_prompt_projects__project_id__prompts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_projects__project_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Responses */
        get: operations["list_responses_runs__run_id__responses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditCreate */
        AuditCreate: {
            /** Project Id */
            project_id?: string | null;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** AuditOut */
        AuditOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Project Id */
            project_id: string | null;
            /** Score */
            score: number | null;
            /** Status */
            status: string;
            /** Url */
            url: string;
        };
        /** BrandCreate */
        BrandCreate: {
            /**
             * Aliases
             * @default []
             */
            aliases?: string[];
            /**
             * Domains
             * @default []
             */
            domains?: string[];
            /**
             * Is Competitor
             * @default false
             */
            is_competitor?: boolean;
            /** Name */
            name: string;
        };
        /** BrandMetricsOut */
        BrandMetricsOut: {
            /** Avg Position */
            avg_position: number | null;
            /**
             * Brand Id
             * Format: uuid
             */
            brand_id: string;
            /** Brand Name */
            brand_name: string;
            citation_rate: components["schemas"]["RatioOut"];
            /** Engine Id */
            engine_id: string;
            /** Is Competitor */
            is_competitor: boolean;
            mention_rate: components["schemas"]["RatioOut"];
            /** Share Of Voice */
            share_of_voice: number | null;
            /** Visibility Score */
            visibility_score: number;
        };
        /** BrandOut */
        BrandOut: {
            /**
             * Aliases
             * @default []
             */
            aliases: string[];
            /**
             * Domains
             * @default []
             */
            domains: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Competitor
             * @default false
             */
            is_competitor: boolean;
            /** Name */
            name: string;
        };
        /** CitationOut */
        CitationOut: {
            /** Title */
            title: string | null;
            /** Url */
            url: string;
        };
        /** DailyPointOut */
        DailyPointOut: {
            /** Avg Position */
            avg_position: number | null;
            /**
             * Brand Id
             * Format: uuid
             */
            brand_id: string;
            /** Brand Name */
            brand_name: string;
            citation_rate: components["schemas"]["RatioOut"];
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Engine Id */
            engine_id: string;
            /** Is Competitor */
            is_competitor: boolean;
            mention_rate: components["schemas"]["RatioOut"];
            /** Share Of Voice */
            share_of_voice: number | null;
            /** Visibility Score */
            visibility_score: number;
        };
        /** EngineOut */
        EngineOut: {
            /** Display Name */
            display_name: string;
            /** Fidelity */
            fidelity: string;
            /** Id */
            id: string;
            /** Mode */
            mode: string;
            /** Region */
            region: string;
        };
        /** FindingOut */
        FindingOut: {
            /** Category */
            category: string;
            /** Message */
            message: string;
            /** Recommendation */
            recommendation: string | null;
            /** Rule Id */
            rule_id: string;
            /** Severity */
            severity: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /**
             * Default Locale
             * @default zh-CN
             */
            default_locale?: string;
            /** Name */
            name: string;
            /** Primary Domain */
            primary_domain?: string | null;
        };
        /** ProjectMetricsOut */
        ProjectMetricsOut: {
            /** Daily */
            daily: components["schemas"]["DailyPointOut"][];
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Summary */
            summary: components["schemas"]["BrandMetricsOut"][];
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Brands
             * @default []
             */
            brands: components["schemas"]["BrandOut"][];
            /**
             * Default Locale
             * @default zh-CN
             */
            default_locale: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Primary Domain */
            primary_domain: string | null;
            /**
             * Prompts
             * @default []
             */
            prompts: components["schemas"]["PromptOut"][];
        };
        /** PromptCreate */
        PromptCreate: {
            /** Locale */
            locale?: string | null;
            /** Text */
            text: string;
            /** Topic */
            topic?: string | null;
        };
        /** PromptOut */
        PromptOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Locale */
            locale: string | null;
            /** Text */
            text: string;
            /** Topic */
            topic: string | null;
        };
        /** RatioOut */
        RatioOut: {
            /** Ci High */
            ci_high: number;
            /** Ci Low */
            ci_low: number;
            /** N */
            n: number;
            /** Value */
            value: number;
        };
        /**
         * ResponseOut
         * @description Also the DTO other modules receive via public.get_response().
         */
        ResponseOut: {
            /** Answer Text */
            answer_text: string;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Engine Id */
            engine_id: string;
            /** Fidelity */
            fidelity: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Model */
            model: string | null;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Prompt Id
             * Format: uuid
             */
            prompt_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** RunCreate */
        RunCreate: {
            /** Engines */
            engines: string[];
            /** Samples Per Prompt */
            samples_per_prompt?: number | null;
        };
        /** RunOut */
        RunOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Done Tasks */
            done_tasks: number;
            /** Engines */
            engines: string[];
            /** Failed Tasks */
            failed_tasks: number;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Samples Per Prompt */
            samples_per_prompt: number;
            /** Status */
            status: string;
            /** Total Tasks */
            total_tasks: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audits_audits_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_audit_audits_post: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_audits__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_engines_engines_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_brand_projects__project_id__brands_post: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_projects__project_id__metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMetricsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_prompt_projects__project_id__prompts_post: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_projects__project_id__runs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_responses_runs__run_id__responses_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-id"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
