"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 09:14:25.170669
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzed_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('collected_on', sa.Date(), nullable=False),
    sa.Column('analyzer_version', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyzed_responses')),
    sa.UniqueConstraint('response_id', name=op.f('uq_analyzed_responses_response_id'))
    )
    op.create_index(op.f('ix_analyzed_responses_collected_on'), 'analyzed_responses', ['collected_on'], unique=False)
    op.create_index(op.f('ix_analyzed_responses_project_id'), 'analyzed_responses', ['project_id'], unique=False)
    op.create_index(op.f('ix_analyzed_responses_workspace_id'), 'analyzed_responses', ['workspace_id'], unique=False)
    op.create_table('audit_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_jobs'))
    )
    op.create_index(op.f('ix_audit_jobs_project_id'), 'audit_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_jobs_workspace_id'), 'audit_jobs', ['workspace_id'], unique=False)
    op.create_table('metric_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('n_responses', sa.Integer(), nullable=False),
    sa.Column('n_mentioned', sa.Integer(), nullable=False),
    sa.Column('n_cited', sa.Integer(), nullable=False),
    sa.Column('position_sum', sa.Integer(), nullable=False),
    sa.Column('total_brand_mentions', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_daily')),
    sa.UniqueConstraint('project_id', 'brand_id', 'engine_id', 'day', name=op.f('uq_metric_daily_project_id_brand_id_engine_id_day'))
    )
    op.create_index(op.f('ix_metric_daily_project_id'), 'metric_daily', ['project_id'], unique=False)
    op.create_index(op.f('ix_metric_daily_workspace_id'), 'metric_daily', ['workspace_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('primary_domain', sa.String(length=255), nullable=True),
    sa.Column('default_locale', sa.String(length=16), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('engines', sa.JSON(), nullable=False),
    sa.Column('samples_per_prompt', sa.Integer(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('done_tasks', sa.Integer(), nullable=False),
    sa.Column('failed_tasks', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_runs_workspace_id'), 'runs', ['workspace_id'], unique=False)
    op.create_table('usage_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_ledger'))
    )
    op.create_index(op.f('ix_usage_ledger_workspace_id'), 'usage_ledger', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('slug', name=op.f('uq_workspaces_slug'))
    )
    op.create_table('audit_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['audit_jobs.id'], name=op.f('fk_audit_findings_job_id_audit_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_findings'))
    )
    op.create_index(op.f('ix_audit_findings_job_id'), 'audit_findings', ['job_id'], unique=False)
    op.create_index(op.f('ix_audit_findings_workspace_id'), 'audit_findings', ['workspace_id'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=False),
    sa.Column('is_competitor', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_brands_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    op.create_index(op.f('ix_brands_project_id'), 'brands', ['project_id'], unique=False)
    op.create_index(op.f('ix_brands_workspace_id'), 'brands', ['workspace_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('analyzer_version', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyzed_responses.id'], name=op.f('fk_citations_analysis_id_analyzed_responses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations'))
    )
    op.create_index(op.f('ix_citations_analysis_id'), 'citations', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_citations_domain'), 'citations', ['domain'], unique=False)
    op.create_index(op.f('ix_citations_workspace_id'), 'citations', ['workspace_id'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.Double(), nullable=True),
    sa.Column('analyzer_version', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyzed_responses.id'], name=op.f('fk_mentions_analysis_id_analyzed_responses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentions'))
    )
    op.create_index(op.f('ix_mentions_analysis_id'), 'mentions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_mentions_brand_id'), 'mentions', ['brand_id'], unique=False)
    op.create_index(op.f('ix_mentions_workspace_id'), 'mentions', ['workspace_id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_prompts_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts'))
    )
    op.create_index(op.f('ix_prompts_project_id'), 'prompts', ['project_id'], unique=False)
    op.create_index(op.f('ix_prompts_workspace_id'), 'prompts', ['workspace_id'], unique=False)
    op.create_table('query_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('sample_idx', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_uri', sa.String(length=1024), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_query_tasks_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_tasks')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_query_tasks_idempotency_key'))
    )
    op.create_index(op.f('ix_query_tasks_run_id'), 'query_tasks', ['run_id'], unique=False)
    op.create_index(op.f('ix_query_tasks_workspace_id'), 'query_tasks', ['workspace_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('fidelity', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('raw_uri', sa.String(length=1024), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_responses_run_id_runs')),
    sa.ForeignKeyConstraint(['task_id'], ['query_tasks.id'], name=op.f('fk_responses_task_id_query_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responses')),
    sa.UniqueConstraint('task_id', name=op.f('uq_responses_task_id'))
    )
    op.create_index(op.f('ix_responses_project_id'), 'responses', ['project_id'], unique=False)
    op.create_index(op.f('ix_responses_run_id'), 'responses', ['run_id'], unique=False)
    op.create_index(op.f('ix_responses_workspace_id'), 'responses', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_workspace_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_run_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_project_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_query_tasks_workspace_id'), table_name='query_tasks')
    op.drop_index(op.f('ix_query_tasks_run_id'), table_name='query_tasks')
    op.drop_table('query_tasks')
    op.drop_index(op.f('ix_prompts_workspace_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_project_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_mentions_workspace_id'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_brand_id'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_analysis_id'), table_name='mentions')
    op.drop_table('mentions')
    op.drop_index(op.f('ix_citations_workspace_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_domain'), table_name='citations')
    op.drop_index(op.f('ix_citations_analysis_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_brands_workspace_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_project_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_audit_findings_workspace_id'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_job_id'), table_name='audit_findings')
    op.drop_table('audit_findings')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_usage_ledger_workspace_id'), table_name='usage_ledger')
    op.drop_table('usage_ledger')
    op.drop_index(op.f('ix_runs_workspace_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_metric_daily_workspace_id'), table_name='metric_daily')
    op.drop_index(op.f('ix_metric_daily_project_id'), table_name='metric_daily')
    op.drop_table('metric_daily')
    op.drop_index(op.f('ix_audit_jobs_workspace_id'), table_name='audit_jobs')
    op.drop_index(op.f('ix_audit_jobs_project_id'), table_name='audit_jobs')
    op.drop_table('audit_jobs')
    op.drop_index(op.f('ix_analyzed_responses_workspace_id'), table_name='analyzed_responses')
    op.drop_index(op.f('ix_analyzed_responses_project_id'), table_name='analyzed_responses')
    op.drop_index(op.f('ix_analyzed_responses_collected_on'), table_name='analyzed_responses')
    op.drop_table('analyzed_responses')
    # ### end Alembic commands ###
